package com.belaku.knowing

data class RetweetStatus(
    val binding_values: Any,
    val bookmark_count: Int,
    val community_note: Any,
    val conversation_id: String,
    val creation_date: String,
    val expanded_url: Any,
    val extended_entities: ExtendedEntitiesX,
    val favorite_count: Int,
    val in_reply_to_status_id: Any,
    val language: String,
    val media_url: List<String>,
    val quote_count: Int,
    val quoted_status: Any,
    val quoted_status_id: Any,
    val reply_count: Int,
    val retweet: Boolean,
    val retweet_count: Int,
    val retweet_status: Any,
    val retweet_tweet_id: Any,
    val source: Any,
    val text: String,
    val timestamp: Int,
    val tweet_id: String,
    val user: UserX,
    val video_url: Any,
    val video_view_count: Any,
    val views: Int
)